# -*- coding: utf-8 -*-
"""Scraping-BPML-Sentimen-Analysis-Minecraft.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nf0g_Sd7RlgLndeNbUw9XKNa5ichB_6e

Name: Hendra<br>
Email: hendradrakho@gmail.com<br>
Runtime: Google Colab Local Runtime<br>
CPU: AMD Ryzen 5 7640hs<br>
GPU: Nvidia RTX 4060 Mobile<br>
"""

!pip install google-play-scraper

!pip install pydrive2 google-auth google-auth-oauthlib google-auth-httplib2

# Using Local Runtime (Google-Drive) Not Supported
# from google.colab import drive
# drive.mount('/content/drive')

mkdir -p drive

mkdir -p drive/MyDrive

cd /content/drive/MyDrive

mkdir -p Dicoding-Machine-Learning

cd Dicoding-Machine-Learning

mkdir -p SentimentAnalysisSubmission2025

cd SentimentAnalysisSubmission2025

mkdir -p dataset

mkdir -p glove

pwd

from google_play_scraper import Sort, reviews
import matplotlib.pyplot as plt
from textblob import TextBlob
import pandas as pd
import random

datasetDir = 'dataset/'
rawDatasetName = 'googleplay_minecraft_US_reviews_raw.csv'

apps = 'com.mojang.minecraftpe'
scrap_len = 150000
pick_rating = [1, 2, 3, 5]

# Function to Scrap Review from Google-Play

def scrapGooglePlayReview():
  scrapReview = []
  scrap_len_per_rating = scrap_len // len(pick_rating)

  print("Scrap Rating", pick_rating)
  print("Total Scrap Length:", scrap_len)
  print("Scrap Apps:", apps)
  print("Scrap per rating: ", scrap_len_per_rating)

  # scrap review with score 1, 2, 3 and 5
  for score in pick_rating:
    print('===========================================')
    print('scrap rating: ', score)

    raw, _ = reviews(
        apps,
        lang = 'en',
        country = 'us',
        sort= Sort.RATING,
        count = scrap_len_per_rating,
        filter_score_with = score
    )

    scrapReview.extend(raw)

    print('done scrap rating: ', score)
    print('scrapped: ', len(raw), 'items')
    print('===========================================')

  print('Total Raw Dataset:', len(scrapReview))

  # Make dataframe
  raw_df = pd.DataFrame(scrapReview)
  reviews_df = raw_df[['content']]

  return reviews_df.sample(frac=1).reset_index(drop=True)

# Scrap Google Play Reviews

raw_df = scrapGooglePlayReview()
raw_df.head()

# Show Dataset

raw_df.head()

# Save Dataset
raw_df.to_csv(datasetDir + rawDatasetName, index=False, encoding='utf-8')